package ru.betboom.tests;// Generated by Selenium IDE

import org.junit.Test;


public class FirstTest extends TestBase {

  @Test
  public void regTest() {
    app.getLoginHelper().findAuthButton();
    app.getLoginHelper().fillForm("9061112233", "12345678");
    app.getLoginHelper().sendForm();
  }

}
