package ru.betboom;// Generated by Selenium IDE

import org.junit.Test;


public class FirstTest extends TestBase {

  @Test
  public void regTest() {
    findAuthButton();
    fillForm("9061112233", "12345678");
    sendForm();
  }

}
