package qa.betboom;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.testng.TestNGAntTask.Mode.junit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class regTest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void betboom1() {
    driver.findElement(By.cssSelector(".js-toggle-account-settings use")).click();
    driver.findElement(By.cssSelector(".account-menu:nth-child(2) > .account-menu__item--exit .account-menu__title")).click();
    driver.findElement(By.linkText("Регистрация")).click();
    driver.findElement(By.id("reg_login_input")).click();
    driver.findElement(By.id("reg_login_input")).sendKeys("+7 (111) 111-11-11");
    driver.findElement(By.id("reg_pass_input")).click();
    driver.findElement(By.id("reg_pass_input")).sendKeys("11111111");
    driver.findElement(By.cssSelector(".form-group:nth-child(4) .control-checkbox__label")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(5) .control-checkbox__label")).click();
    driver.findElement(By.id("button_reg")).click();
    driver.findElement(By.id("reg_sms_input")).click();
    driver.findElement(By.id("reg_sms_input")).sendKeys("0");
    driver.findElement(By.cssSelector(".js-gtm-click-sms-next")).click();
    driver.findElement(By.id("reg_qiwidoc_number")).click();
    driver.findElement(By.id("reg_qiwidoc_number")).sendKeys("1111");
    driver.findElement(By.cssSelector(".js-gtm-click-sms-next")).click();
    driver.findElement(By.id("reg_qiwidoc_number")).click();
    driver.findElement(By.cssSelector(".js-reg-popup-sms form")).click();
    driver.findElement(By.id("reg_qiwidoc_number")).sendKeys("2222");
    driver.findElement(By.cssSelector(".js-gtm-click-sms-next")).click();
    driver.findElement(By.cssSelector(".js-reg-popup-sms form")).click();
    driver.findElement(By.id("reg_qiwidoc_number")).sendKeys("5465");
    driver.findElement(By.cssSelector(".js-gtm-click-sms-next")).click();
    driver.findElement(By.cssSelector(".js-reg-popup-processing .icon")).click();
    driver.get("https://bboncyp-onl-1.bb-online-stage.com/");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    driver.findElement(By.linkText("Вход")).click();
    driver.findElement(By.id("login_input")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(4) > .btn--primary")).click();
  }
}
